spring.application.name=JwtProject
spring.datasource.url=jdbc:mysql://localhost:3306/college_db_jwt
spring.datasource.username=root
spring.datasource.password=MySQL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8082

jwt.secret= ThisisRBUProjectforJWTAuthentication0123456789wxdewgywtuh6754wbyh5wrw46w